version: 3

project:
  id: cadenzaflow/cadenzaflow-modeler
  labels:
  - cadenzaflow-modeler
  - modeler
  policy: CadenzaFlow Distribution
  url: https://github.com/cadenzaflow/cadenzaflow-modeler

paths:
  exclude:
  - ./resources
